### ISSUE TITLE
Paginating rados_objects_list

### ISSUE THREAD

**Issue by JANorman** [ceph/phprados#23]
Hi,

Are there any plans to add support for limit and offset operators to the `rados_objects_list` function, so that it matches the [lower level API methods](http://docs.ceph.com/docs/master/rados/api/librados/#rados_object_list)?

For example it would be handy to ahve something like:
````php
// Get the first 100 objects
rados_objects_list($io, 0, 100);
````

This would be helpful because you may not want to return all of the objects at once (e.g. for pagination).

Thanks

**Comment by wido** [comment]
Ah, those calls are new to me! Did not know librados supported that.

Honestly, I haven't looked at phprados for some time and I don't think I'll be able to work on this.

A pull request is welcome and I'm happy to review it. You might want to give it a try?

**Comment by JANorman** [comment]
OK — I will look at extending the functionality.

**Comment by wido** [comment]
Thanks @JANorman !

When you think something is ready, feel free to send a Pull Request. I'll review it and give feedback. Don't hesitate if you don't think it's perfect yet, that's where feedback is for :)

**Comment by JANorman** [comment]
Apologies for the delay - I'll get some tests added.
