### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by wido** [ceph/phprados#25]
In the php7-master and in #21 this was mentioned.

Is this something which can be merged into master @wenduo ?

**Comment by wido** [comment]
@wenduo A rados_pconnect() could be something useful I agree. Not sure how this would be implemented, but I can understand it can improve performance vastly.

**Comment by wenduo** [comment]
@wido  Then I will make a pull request with thread-safe pconnect and we can discuss on that, but it might need some time. 
              As for php7,I am not sure which is better: mergeing php-7 code into master or maintaining a different branch. Because it's hard to update php in some system,and they remain in php5/6, make master branch runnable with php5/6 is kind of feature from my view.

**Comment by wenduo** [comment]
@wido  But I think merging php-7 into master is also a good choice ,which choice do you perfer?

**Comment by wido** [comment]
@wenduo We could always do a latest release from master which works on 5.5 and 5.6 and then make master php7, right?

**Comment by wenduo** [comment]
@wido Yeah, I can understand that. So, I will merge php7 into master after test with 5.5/5.6

**Comment by wido** [comment]
Ok, great. Might wait for #23 to be merged first and then cut off towards PHP 7.

**Comment by wido** [comment]
With a recent PR PHP 7.1 is also supported
