### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xiyusullos** [ceph/phprados#27]
make: *** [rados.lo] Error 1

**Comment by wido** [comment]
Thanks for the report! Can you tell me with which version of librados this is? What is your OS/distro?

**Comment by xiyusullos** [comment]
The latest one. PHP version is 7.1.1. Linux is ubuntu 14.04.3.

**Comment by wido** [comment]
Can you post a more full output of the make, since I don't have a test env for this right now.

**Comment by xiyusullos** [comment]
I'm so sorry about my bad description. 
Here's the log.
[phprados.txt](https://github.com/ceph/phprados/files/1116810/phprados.txt)

**Comment by wido** [comment]
Seems to be a PHP 7.0 problem. I haven't worked on the module for some time and probably won't be able to do in the near future.

If you could fix this by sending a Pull Request that would be very great!

**Comment by wido** [comment]
Oh, I forgot, did you check the php7-master branch? Might be that that works. That needs to go to master I think.
