### ISSUE TITLE
PHP Fatal error This function can't be called when not connected in

### ISSUE THREAD

**Issue by sjuliper7** [ceph/phprados#34]
I have code like this, hello.php 

`<?php
$rados = rados_create();
rados_conf_read_file($rados, '/etc/ceph/ceph.conf');
rados_connect($rados);
foreach (rados_pool_list($rados) as $pool) {
    echo $pool."\n";
}
rados_shutdown($rados);
`
when i'm run with `sudo php hello.php` is run as well, but when i'm running without `sudo` it's show error like this `PHP Fatal error:  rados_pool_list(): This function can't be called when not connected`

Do i need to change the config, and how? Thank you

**Comment by matang-dave** [comment]
Hi @sjuliper7, does you config file have the read access for the user from which you are running `php hello.php`  ?

**Comment by sjuliper7** [comment]
Hello Mr @matang-dave  , i have set change the file permission to 644, and i try to run the file, `PHP Fatal error: rados_pool_list(): This function can't be called when not connected`

**Comment by matang-dave** [comment]
Can you please check what is the return value of ```rados_connect($rados)```. In case of error, it should return you an object with error description.

**Comment by sjuliper7** [comment]
when i'm run without sudo `php hello.php`
the error is `array(2) {
  ["errCode"]=>
  int(2)
  ["errMessage"]=>
  string(25) "No such file or directory"
}
`
when with sudo 'sudo php hello.php'
`bool(true)`

and my code : 
`<?php

$rados = rados_create();
rados_conf_read_file($rados, '/etc/ceph/ceph.conf');
$check =  rados_connect($rados);

var_dump($check);

rados_shutdown($rados);

?>
`

**Comment by matang-dave** [comment]
Hmm, now it is clear that non-sudo user does not have access to the file. 
Can you please also check the permission on the directory level also?

**Comment by sjuliper7** [comment]
hello @matang-dave ,
this my  permission level `-rw-r--r--  1 root  root   166 Jun 14 08:14 hello.php`

**Comment by matang-dave** [comment]
No, I am talking about the permission of config and the all the folder above it. `/etc/ceph/ceph.conf`
This StackOverflow article should help you.
https://stackoverflow.com/questions/3740152/how-do-i-change-permissions-for-a-folder-and-all-of-its-subfolders-and-files-in

**Comment by sjuliper7** [comment]
Hello @matang-dave ,
do you mean this..?
`-rw-------  1 root root  151 Jun 14 07:36 ceph.client.admin.keyring
-rw-r--r--  1 root root  266 Jun 14 07:03 ceph.conf
-rw-r--r--  1 root root   92 Nov 19  2018 rbdmap
-rw-------  1 root root    0 Mei 22 13:12 tmpHXEpLx
-rw-------  1 root root    0 Mei 22 13:27 tmpkp7Cmp
-rw-------  1 root root    0 Mei 22 13:23 tmppj2BwC
-rw-------  1 root root    0 Mei 22 13:24 tmprFzcau`
